local M = {}

M.mason = {
  package_pending = " ",
  package_installed = "󰄳 ",
  package_uninstalled = " 󰚌",
}

M.cmp_kind = {
  Class = "󰠱",
  Color = " ",
  Constant = "",
  Constructor = " ",
  Default = " ",
  Enum = "",
  EnumMember = " ",
  Event = " ",
  Field = "󰜢",
  File = "󰈚",
  Folder = " ",
  Function = " ",
  Keyword = " ",
  Interface = "",
  Implementation = "",
  Method = "󰆧",
  Module = "",
  Namespace = "󰌗",
  Number = "",
  Operator = "󰆕",
  Property = " ",
  Reference = "󰈇",
  Snippet = " ", -- ""," "," "
  Struct = "󰙅",
  Text = "󰉿",
  TypeParameter = "  ",
  Undefined = "",
  Unit = "󰑭",
  Value = "󰎠",
  Variable = "󰀫",
  TypeAlias = "",
  Parameter = "",
  StaticMethod = "",
  Macro = "",
}

M.icons = {
  error = " ",
  warn = " ",
  info = "",
  hint = " ",
  code_action = "",
  code_lens_action = "󰄄",
  test = "",
  docs = "",
  clock = "󰥔 ",
  calendar = " ",
  buffer = " ",
  settings = " ",
  ls_inactive = "󰒎 ",
  ls_active = "󰒍 ",
  question = " ",
  screen = "󰐯",
  dart = " ",
  config = " ",
  git = " ",
  magic = " ",
  exit = " ",
  repo = "",
  term = " ",
}

M.nvim_tree_icons = {
  default = "",
  symlink = "",
  git = {
    unmerged = "",
    added = "",
    deleted = "",
    modified = "",
    renamed = "",
    untracked = "",
    ignored = "",
    unstaged = "󱍯",
    staged = "",
    conflict = "",
  },
  folder = {
    arrow_closed = "",
    arrow_open = "",
    default = "",
    open = "",
    empty = "",
    empty_open = "",
    symlink = "",
    symlink_open = "",
  },
}

M.symbols_outline = {
  File = "󰈚",
  Module = "",
  Namespace = "󰌗",
  Package = "",
  Class = "󰠱",
  Method = "ƒ",
  Property = "",
  Field = "󰜢",
  Constructor = "",
  Enum = "",
  Interface = " ",
  Function = "",
  Variable = "",
  Constant = "",
  String = "𝓐",
  Number = "#",
  Boolean = "⊨",
  Array = "[]",
  Object = "⦿",
  Key = "",
  Null = "NULL",
  EnumMember = "",
  Struct = "󰙅",
  Event = "",
  Operator = "󰆕",
  TypeParameter = "𝙏",
}

M.todo_comments = {
  FIX = " ",
  TODO = " ",
  HACK = " ",
  WARN = " ",
  PERF = " ",
  NOTE = " ",
  ERROR = " ",
  REFS = "",
  SHIELD = "",
}

M.numbers = {
  "󰼏 ",
  "󰼐 ",
  "󰼑 ",
  "󰼒 ",
  "󰼓 ",
  "󰼔 ",
  "󰼕 ",
  "󰼖 ",
  "󰼗 ",
  "󰿪 ",
}

M.file_icons = {
  Brown = { "" },
  Aqua = { "" },
  LightBlue = { "", "" },
  Blue = { "", "", "", "", "", "", "", "", "", "", "", "", "" },
  DarkBlue = { "", "" },
  Purple = { "", "", "", "", "" },
  Red = { "", "", "", "", "", "" },
  Beige = { "", "", "" },
  Yellow = { "", "", "λ", "", "" },
  Orange = { "", "" },
  DarkOrange = { "", "", "", "", "" },
  Pink = { "", "" },
  Salmon = { "" },
  Green = { "", "", "", "", "", "" },
  LightGreen = { "", "", "", "﵂" },
  White = { "", "", "", "", "", "" },
}

return M
